// 
// Decompiled by Procyon v0.6.0
// 

public final class cs
{
    public int A;
    public int B;
    public int C;
    public int D;
    public int E;
    public int F;
    public int G;
    public int H;
    public int I;
    public int J;
    public int K;
    public int L;
    public int M;
    public float N;
    public float O;
    public int P;
    public int Q;
    public float R;
    public boolean S;
    public float T;
    public float U;
    public float V;
    public float W;
    public float X;
    public float Y;
    public float Z;
    boolean a;
    public float aa;
    public float ab;
    public float ac;
    public int ad;
    public int ae;
    public int af;
    public int ag;
    public int ah;
    public int ai;
    public int b;
    public int c;
    int d;
    public int e;
    public int f;
    public float g;
    public int h;
    public int i;
    public int j;
    public int k;
    public int l;
    public int m;
    public int n;
    public int o;
    public int p;
    public int q;
    public int r;
    public int s;
    public int t;
    public float u;
    public float v;
    public String w;
    public int x;
    public int y;
    public int z;
    
    public cs() {
        this.a = false;
        this.e = -1;
        this.f = -1;
        this.g = -1.0f;
        this.h = -1;
        this.i = -1;
        this.j = -1;
        this.k = -1;
        this.l = -1;
        this.m = -1;
        this.n = -1;
        this.o = -1;
        this.p = -1;
        this.q = -1;
        this.r = -1;
        this.s = -1;
        this.t = -1;
        this.u = 0.5f;
        this.v = 0.5f;
        this.w = null;
        this.x = -1;
        this.y = -1;
        this.z = -1;
        this.A = -1;
        this.B = -1;
        this.C = -1;
        this.D = -1;
        this.E = -1;
        this.F = -1;
        this.G = 0;
        this.H = -1;
        this.I = -1;
        this.J = -1;
        this.K = -1;
        this.L = -1;
        this.M = -1;
        this.N = 0.0f;
        this.O = 0.0f;
        this.P = 0;
        this.Q = 0;
        this.R = 1.0f;
        this.S = false;
        this.T = 0.0f;
        this.U = 0.0f;
        this.V = 0.0f;
        this.W = 1.0f;
        this.X = 1.0f;
        this.Y = 0.0f;
        this.Z = 0.0f;
        this.aa = 0.0f;
        this.ab = 0.0f;
        this.ac = 0.0f;
        this.ad = -1;
        this.ae = -1;
        this.af = -1;
        this.ag = -1;
        this.ah = -1;
        this.ai = -1;
    }
    
    public final void a(final cr cr) {
        cr.d = this.h;
        cr.e = this.i;
        cr.f = this.j;
        cr.g = this.k;
        cr.h = this.l;
        cr.i = this.m;
        cr.j = this.n;
        cr.k = this.o;
        cr.l = this.p;
        cr.m = this.q;
        cr.n = this.r;
        cr.o = this.s;
        cr.p = this.t;
        cr.leftMargin = this.A;
        cr.rightMargin = this.B;
        cr.topMargin = this.C;
        cr.bottomMargin = this.D;
        cr.u = this.M;
        cr.v = this.L;
        cr.w = this.u;
        cr.x = this.v;
        cr.y = this.w;
        cr.K = this.x;
        cr.L = this.y;
        cr.B = this.N;
        cr.A = this.O;
        cr.D = this.Q;
        cr.C = this.P;
        cr.E = this.ad;
        cr.F = this.ae;
        cr.I = this.af;
        cr.J = this.ag;
        cr.G = this.ah;
        cr.H = this.ai;
        cr.M = this.z;
        cr.c = this.g;
        cr.a = this.e;
        cr.b = this.f;
        cr.width = this.b;
        cr.height = this.c;
        cr.setMarginStart(this.F);
        cr.setMarginEnd(this.E);
        cr.a();
    }
}
