import java.util.Map;

// 
// Decompiled by Procyon v0.6.0
// 

public final class cwv
{
    public static final cxm A;
    public static final cxm B;
    public static final cxm C;
    public static final cxm D;
    public static final cxm E;
    public static final cxm F;
    public static final cxm G;
    public static final cxm H;
    public static final cxm I;
    public static final cxm J;
    public static final cxm K;
    public static final cxm L;
    public static final cxm M;
    public static final cxm N;
    public static final cxm O;
    public static final cxm P;
    public static final cxm Q;
    public static final cxm R;
    public static final cxm S;
    public static final cxm T;
    public static final cxm U;
    public static final cxm V;
    public static final cxm W;
    public static final cxo a;
    public static final cxo b;
    public static final cxo c;
    public static final cxo d;
    public static final cxo e;
    public static final cxo f;
    public static final cxo g;
    public static final cxo h;
    public static final cxo i;
    public static final cxo j;
    public static final cxo k;
    public static final cxm l;
    public static final cxm m;
    public static final cxm n;
    public static final cxm o;
    public static final cxm p;
    public static final cxm q;
    public static final cxm r;
    public static final cxm s;
    public static final cxm t;
    public static final cxm u;
    public static final cxm v;
    public static final cxm w;
    public static final cxm x;
    public static final cxm y;
    public static final cxm z;
    
    static {
        final cxn cxn = new cxn();
        cxn.a = "camcorder.bitrate";
        a = cxn.a();
        final cxn cxn2 = new cxn();
        cxn2.a = "camcorder.capture_rate";
        final Integer value = 0;
        final Integer value2 = 240;
        cxn2.c = noi.L(value, 30, 60, 120, value2);
        b = cxn2.a();
        final cxn cxn3 = new cxn();
        cxn3.a = "detect_face_on_front_camera";
        l = cxn3.f();
        final cxn cxn4 = new cxn();
        cxn4.a = "detect_face_on_non_front_camera";
        m = cxn4.f();
        final cxn cxn5 = new cxn();
        cxn5.a = "camcorder_slowmo.fs";
        n = cxn5.c();
        new cxn().a = "camcorder.h265";
        final cxn cxn6 = new cxn();
        cxn6.a = "enable_hevc_setting";
        o = cxn6.f();
        final cxn cxn7 = new cxn();
        cxn7.a = "camcorder.codec_sm";
        p = cxn7.f();
        final cxn cxn8 = new cxn();
        cxn8.a = "camcorder.codec_video";
        q = cxn8.f();
        new cxn().a = "camcorder.no_audio";
        new cxn().a = "camcorder.enable_sapphire";
        final cxn cxn9 = new cxn();
        cxn9.a = "camcorder.ois";
        r = cxn9.d();
        final cxn cxn10 = new cxn();
        cxn10.a = "camcorder.stereo";
        s = cxn10.d();
        new cxn().a = "camcorder.sf_share";
        final cxn cxn11 = new cxn();
        cxn11.a = "camcorder.trk_yuv";
        t = cxn11.c();
        new cxn().a = "camcorder.viewfinder_effect";
        final cxn cxn12 = new cxn();
        cxn12.a = "fps_video_setting_writeable";
        u = cxn12.f();
        final cxn cxn13 = new cxn();
        cxn13.a = "google_llv_30_fps_non_4k";
        v = cxn13.f();
        final cxn cxn14 = new cxn();
        cxn14.a = "google_llv_auto_fps_non_4k";
        w = cxn14.f();
        final cxn cxn15 = new cxn();
        cxn15.a = "max_1080p_video_duration_seconds";
        c = cxn15.a();
        final cxn cxn16 = new cxn();
        cxn16.a = "max_2160p_video_duration_seconds";
        d = cxn16.a();
        final cxn cxn17 = new cxn();
        cxn17.a = "max_hfr_video_duration_seconds";
        e = cxn17.a();
        final cxn cxn18 = new cxn();
        cxn18.a = "UNLOCK_AF_AE_WITH_SCENE_CHANGE_FOR_FRONT_CAM";
        x = cxn18.f();
        final cxn cxn19 = new cxn();
        cxn19.a = "camcorder.vidqual_front";
        final Integer value3 = 144;
        final Integer value4 = 288;
        final Integer value5 = 480;
        final Integer value6 = 720;
        final Integer value7 = 1080;
        final Integer value8 = 2160;
        cxn19.c = noi.M(value3, value2, value4, value5, value6, value7, value8);
        f = cxn19.a();
        final cxn cxn20 = new cxn();
        cxn20.a = "camcorder.vidqual_back";
        cxn20.c = noi.M(value3, value2, value4, value5, value6, value7, value8);
        g = cxn20.a();
        final cxn cxn21 = new cxn();
        cxn21.a = "zoom_override_enabled";
        y = cxn21.f();
        final cxn cxn22 = new cxn();
        cxn22.a = "camcorder.max_zoom_30fps";
        z = cxn22.e();
        final cxn cxn23 = new cxn();
        cxn23.a = "camcorder.max_zoom_default";
        A = cxn23.e();
        final cxn cxn24 = new cxn();
        cxn24.a = "camcorder_prewire_record_surface";
        B = cxn24.f();
        final cxn cxn25 = new cxn();
        cxn25.a = "camcorder_recorder_warm_up";
        C = cxn25.f();
        new cxn().a = "camcorder.24fps";
        final cxn cxn26 = new cxn();
        cxn26.a = "camcorder.4k60fps";
        D = cxn26.f();
        final cxn cxn27 = new cxn();
        cxn27.a = "camcorder.stokes_dyn";
        E = cxn27.f();
        final cxn cxn28 = new cxn();
        cxn28.a = "camcorder.stokes_thr";
        F = cxn28.f();
        final cxn cxn29 = new cxn();
        cxn29.a = "camcorder.stokes_mra";
        G = cxn29.f();
        new cxn().a = "camcorder.poll";
        final cxn cxn30 = new cxn();
        cxn30.a = "camcorder.submode";
        final Integer value9 = 1;
        final Integer value10 = 2;
        cxn30.c = noi.J(value, value9, value10);
        h = cxn30.a();
        final cxn cxn31 = new cxn();
        cxn31.a = "camcorder.washington_md";
        final Integer value11 = 3;
        cxn31.c = noi.L(value, value9, value10, value11, 4);
        i = cxn31.a();
        final cxn cxn32 = new cxn();
        cxn32.a = "camcorder.enable_dumpling";
        H = cxn32.f();
        new cxn().a = "camcorder.enable_w_poll";
        final cxn cxn33 = new cxn();
        cxn33.a = "camcorder.slowmo_snapshot";
        I = cxn33.f();
        new cxn().a = "camcorder.screenshot_snapshot";
        final cxn cxn34 = new cxn();
        cxn34.a = "camcorder.washington";
        J = cxn34.f();
        final cxn cxn35 = new cxn();
        cxn35.a = "camcorder.washington_edu";
        K = cxn35.f();
        final cxn cxn36 = new cxn();
        cxn36.a = "camcorder.ext_mic_state";
        cxn36.c = noi.K(value, value9, value10, value11);
        j = cxn36.a();
        final cxn cxn37 = new cxn();
        cxn37.a = "camcorder.use_gcamux";
        L = cxn37.f();
        final cxn cxn38 = new cxn();
        cxn38.a = "camcorder.video_file_max_size";
        M = new cxm(cxn38.a, cxn38.b, (float[])null);
        final cxn cxn39 = new cxn();
        cxn39.a = "camcorder.3a_metadata";
        N = cxn39.f();
        final cxn cxn40 = new cxn();
        cxn40.a = "camcorder.fix_crtime";
        O = cxn40.f();
        new cxn().a = "camcorder.fb_preview";
        final cxn cxn41 = new cxn();
        cxn41.a = "camcorder.animate_stab_button";
        P = cxn41.f();
        final cxn cxn42 = new cxn();
        cxn42.a = "camcorder.washington_l";
        Q = cxn42.f();
        final cxn cxn43 = new cxn();
        cxn43.a = "camcorder.washington_a";
        R = cxn43.f();
        final cxn cxn44 = new cxn();
        cxn44.a = "camcorder.washington_c";
        S = cxn44.f();
        final cxn cxn45 = new cxn();
        cxn45.a = "camcorder.slowmo_pause";
        T = cxn45.f();
        final cxn cxn46 = new cxn();
        cxn46.a = "camcorder.sync_fps";
        U = cxn46.f();
        new cxn().a = "camcorder.log_3a";
        final cxn cxn47 = new cxn();
        cxn47.a = "camcorder.auto_stop_on_frame_drop";
        V = cxn47.c();
        final cxn cxn48 = new cxn();
        cxn48.a = "camcorder.camera_perfetto_trace_frame_drops";
        cxn48.b = "General";
        final cxn cxn49 = new cxn();
        cxn49.a = "g";
        cxn49.b = "General";
        k = cxn49.a();
        new cxn().a = "camcorder.ir_fs";
        final cxn cxn50 = new cxn();
        cxn50.a = "camcorder.front_variable_fps_range";
        W = cxn50.f();
        new cxn().a = "camcorder.ts";
        new cxn().a = "camcorder.ap";
        new cxn().a = "camcorder.sm";
        new cxn().a = "camcorder.add_silent_audio";
    }
    
    public static void a(final cxq cxq, final liy liy) {
        cxq.o(cwv.a, null);
        cxq.o(cwv.b, null);
        cxq.s(cwv.l, true);
        cxq.s(cwv.m, true);
        cxq.p(cwv.n);
        cxq.s(cwv.o, true);
        cxq.s(cwv.p, true);
        cxq.s(cwv.q, true);
        cxq.q(cwv.r, true);
        cxq.q(cwv.s, liy.e);
        cxq.p(cwv.t);
        cxq.s(cwv.u, true);
        final cxo c = cwv.c;
        final Integer value = 0;
        cxq.o(c, value);
        cxq.o(cwv.d, value);
        cxq.o(cwv.e, value);
        cxq.s(cwv.v, true);
        cxq.s(cwv.w, true);
        cxq.s(cwv.x, false);
        cxq.o(cwv.f, null);
        cxq.o(cwv.g, null);
        cxq.s(cwv.y, true);
        cxq.r(cwv.z, 5.0f);
        cxq.r(cwv.A, 3.0f);
        cxq.s(cwv.B, false);
        cxq.s(cwv.C, false);
        cxq.s(cwv.D, true);
        cxq.s(cwv.E, false);
        cxq.s(cwv.F, false);
        cxq.s(cwv.G, false);
        cxq.o(cwv.h, 1);
        cxq.s(cwv.I, true);
        cxq.s(cwv.J, true);
        cxq.s(cwv.K, true);
        cxq.o(cwv.j, null);
        cxq.s(cwv.L, true);
        final cxm m = cwv.M;
        final Long value2 = 10737418240L;
        final Map b = ((cyv)cxq).b;
        final String b2 = m.b;
        moh c2;
        if (b2 != null) {
            final String a = m.a;
            final mof a2 = cyr.a;
            final StringBuilder sb = new StringBuilder(b2.length() + 2 + String.valueOf(a).length());
            sb.append(b2);
            sb.append("__");
            sb.append(a);
            c2 = moh.c(a2, sb.toString(), (long)value2, false);
        }
        else {
            c2 = null;
        }
        b.put(m, new cys(value2, c2));
        cxq.s(cwv.N, false);
        cxq.o(cwv.i, null);
        cxq.s(cwv.H, true);
        cxq.s(cwv.O, true);
        cxq.s(cwv.P, false);
        cxq.s(cwv.Q, true);
        cxq.s(cwv.R, true);
        cxq.s(cwv.S, true);
        cxq.s(cwv.T, true);
        cxq.s(cwv.U, false);
        cxq.p(cwv.V);
        final boolean f = liy.f;
        cxq.o(cwv.k, 6);
        cxq.s(cwv.W, true);
    }
}
