// 
// Decompiled by Procyon v0.6.0
// 

public final class cxr
{
    public static final cxo A;
    public static final cxo B;
    public static final cxo C;
    public static final cxo D;
    public static final cxo E;
    public static final cxm F;
    public static final cxm G;
    public static final cxm H;
    public static final cxm I;
    public static final cxm J;
    public static final cxm K;
    public static final cxm L;
    public static final cxm M;
    public static final cxm N;
    public static final cxm O;
    public static final cxm P;
    public static final cxm Q;
    public static final cxm R;
    public static final cxm S;
    public static final cxm T;
    public static final cxm U;
    public static final cxm V;
    public static final cxm W;
    public static final cxm X;
    public static final cxm Y;
    public static final cxm Z;
    public static final cxo a;
    public static final cxm aA;
    public static final cxm aB;
    public static final cxm aC;
    public static final cxm aD;
    public static final cxm aE;
    public static final cxm aF;
    public static final cxm aG;
    public static final cxm aH;
    public static final cxm aI;
    public static final cxm aJ;
    public static final cxm aK;
    public static final cxm aL;
    public static final cxm aM;
    public static final cxm aN;
    public static final cxm aO;
    public static final cxm aP;
    public static final cxm aQ;
    public static final cxm aR;
    public static final cxm aS;
    public static final cxm aT;
    public static final cxm aU;
    public static final cxm aV;
    public static final cxm aW;
    public static final cxm aX;
    public static final cxm aY;
    public static final cxm aZ;
    public static final cxm aa;
    public static final cxm ab;
    public static final cxm ac;
    public static final cxm ad;
    public static final cxm ae;
    public static final cxm af;
    public static final cxm ag;
    public static final cxm ah;
    public static final cxm ai;
    public static final cxm aj;
    public static final cxm ak;
    public static final cxm al;
    public static final cxm am;
    public static final cxm an;
    public static final cxm ao;
    public static final cxm ap;
    public static final cxm aq;
    public static final cxm ar;
    public static final cxm as;
    public static final cxm at;
    public static final cxm au;
    public static final cxm av;
    public static final cxm aw;
    public static final cxm ax;
    public static final cxm ay;
    public static final cxm az;
    public static final cxo b;
    public static final cxm ba;
    public static final cxm bb;
    public static final cxm bc;
    public static final cxm bd;
    public static final cxm be;
    public static final cxm bf;
    public static final cxm bg;
    public static final cxm bh;
    public static final cxm bi;
    public static final cxm bj;
    public static final cxo c;
    public static final cxo d;
    public static final cxo e;
    public static final cxo f;
    public static final cxo g;
    public static final cxo h;
    public static final cxo i;
    public static final cxo j;
    public static final cxo k;
    public static final cxo l;
    public static final cxo m;
    public static final cxo n;
    public static final cxo o;
    public static final cxo p;
    public static final cxo q;
    public static final cxo r;
    public static final cxo s;
    public static final cxo t;
    public static final cxo u;
    public static final cxo v;
    public static final cxo w;
    public static final cxo x;
    public static final cxo y;
    public static final cxo z;
    
    static {
        final cxn cxn = new cxn();
        cxn.a = "camera.scudo_caching";
        F = cxn.f();
        final cxn cxn2 = new cxn();
        cxn2.a = "camera.bind_assistant";
        G = cxn2.f();
        final cxn cxn3 = new cxn();
        cxn3.a = "camera.audio_zoom";
        H = cxn3.f();
        final cxn cxn4 = new cxn();
        cxn4.a = "camera.flash.ind";
        I = cxn4.c();
        final cxn cxn5 = new cxn();
        cxn5.a = "camera.auto_fps_default";
        J = cxn5.f();
        final cxn cxn6 = new cxn();
        cxn6.a = "camera.auto_fps";
        K = cxn6.d();
        final cxn cxn7 = new cxn();
        cxn7.a = "avc_profile_high_supported";
        L = cxn7.f();
        final cxn cxn8 = new cxn();
        cxn8.a = "back_flash_off_by_default";
        M = cxn8.f();
        final cxn cxn9 = new cxn();
        cxn9.a = "blacklisted_resolutions_back";
        N = cxn9.g();
        final cxn cxn10 = new cxn();
        cxn10.a = "blacklisted_resolutions_front";
        O = cxn10.g();
        final cxn cxn11 = new cxn();
        cxn11.a = "blacklisted_preview_resolutions_back";
        P = cxn11.g();
        final cxn cxn12 = new cxn();
        cxn12.a = "blacklisted_preview_resolutions_front";
        Q = cxn12.g();
        new cxn().a = "camera.narrow_cam";
        final cxn cxn13 = new cxn();
        cxn13.a = "camera.p20_lens_setup";
        R = cxn13.f();
        final cxn cxn14 = new cxn();
        cxn14.a = "camera.p21_front_setup";
        S = cxn14.f();
        final cxn cxn15 = new cxn();
        cxn15.a = "camera.toggle_zoom_bar";
        T = cxn15.f();
        final cxn cxn16 = new cxn();
        cxn16.a = "camera_zoom_toggle_long_press_duration_ms";
        cxn16.b = "Zoom";
        a = cxn16.a();
        final cxn cxn17 = new cxn();
        cxn17.a = "camera_zoom_slider_tap_to_show";
        cxn17.b = "Zoom";
        U = cxn17.f();
        new cxn().a = "camera.wide_cam";
        new cxn().a = "camera.chk_anim_trnstns";
        new cxn().a = "camera.disable_phenotype";
        new cxn().a = "camera.disable_clearcut";
        new cxn().a = "camera.clearcut_debug";
        final cxn cxn18 = new cxn();
        cxn18.a = "contact_us_mailing_list_address_default";
        V = cxn18.h();
        final cxn cxn19 = new cxn();
        cxn19.a = "contact_us_mailing_list_address_for_droid_canary_and_fishfood";
        W = cxn19.h();
        final cxn cxn20 = new cxn();
        cxn20.a = "contact_us_mailing_list_address_for_google_food";
        X = cxn20.h();
        new cxn().a = "camera.vid_meta_fatal";
        new cxn().a = "camera.developer.enable";
        final cxn cxn21 = new cxn();
        cxn21.a = "camera.fake_therm_state";
        b = cxn21.a();
        new cxn().a = "camera.ignore_temp";
        new cxn().a = "camera.mock_low_storage";
        final cxn cxn22 = new cxn();
        cxn22.a = "early_focus_unlock";
        Y = cxn22.f();
        final cxn cxn23 = new cxn();
        cxn23.a = "easel_environment_enabled";
        Z = cxn23.f();
        new cxn().a = "camera.elmyra_lens";
        new cxn().a = "camera.photo_fixed_framerate";
        new cxn().a = "camera.elmyra_assist";
        new cxn().a = "camera.debug_hw_ver";
        final cxn cxn24 = new cxn();
        cxn24.a = "exif_model_make_sanitization_enabled";
        aa = cxn24.f();
        new cxn().a = "camera.exp.activity";
        final cxn cxn25 = new cxn();
        cxn25.a = "camera.faceannouncer";
        ab = cxn25.c();
        new cxn().a = "camera.faceboxes";
        final cxn cxn26 = new cxn();
        cxn26.a = "camera.first_preview_frame";
        c = cxn26.a();
        new cxn().a = "camera.debug.overlay";
        new cxn().a = "camera.debug.overlay_info_def";
        new cxn().a = "camera.debug.overlay_info_ff";
        new cxn().a = "camera.debug.overlay_af_saliency";
        new cxn().a = "camera.debug.overlay_af_smartroi";
        final cxn cxn27 = new cxn();
        cxn27.a = "filmstrip_tiny_bounds";
        d = cxn27.a();
        final cxn cxn28 = new cxn();
        cxn28.a = "filmstrip_maximum_smooth_pixels";
        e = cxn28.a();
        new cxn().a = "camera.focus.debug";
        final cxn cxn29 = new cxn();
        cxn29.a = "camera.front.flashColor";
        f = cxn29.a();
        final cxn cxn30 = new cxn();
        cxn30.a = "camera.front_torch_request";
        ac = cxn30.d();
        final cxn cxn31 = new cxn();
        cxn31.a = "camera.front.backgroundIlluminationColor";
        g = cxn31.a();
        final cxn cxn32 = new cxn();
        cxn32.a = "camera.front.viewfinderIlluminationColor";
        h = cxn32.a();
        final cxn cxn33 = new cxn();
        cxn33.a = "camera.front.translucentSelfieIllumination";
        ad = cxn33.f();
        final cxn cxn34 = new cxn();
        cxn34.a = "google_lens_enabled";
        ae = cxn34.f();
        final cxn cxn35 = new cxn();
        cxn35.a = "google_lens_min_supported_photos_app_version";
        af = cxn35.g();
        final cxn cxn36 = new cxn();
        cxn36.a = "camera_hermes_enabled";
        cxn36.b = "General";
        ag = cxn36.f();
        final cxn cxn37 = new cxn();
        cxn37.a = "hermes_activity_finish_millis";
        i = cxn37.a();
        final cxn cxn38 = new cxn();
        cxn38.a = "high_performance_ipe_supported";
        ah = cxn38.f();
        final cxn cxn39 = new cxn();
        cxn39.a = "hybrid_ae_only_ois_jitter_for_back_camera_enabled";
        ai = cxn39.f();
        final cxn cxn40 = new cxn();
        cxn40.a = "hybrid_ae_supported";
        aj = cxn40.f();
        final cxn cxn41 = new cxn();
        cxn41.a = "camera.enable_lkcnry";
        ak = cxn41.c();
        final cxn cxn42 = new cxn();
        cxn42.a = "camera.use_local_logger";
        al = cxn42.f();
        final cxn cxn43 = new cxn();
        cxn43.a = "camera.use_perf_logger";
        am = cxn43.f();
        final cxn cxn44 = new cxn();
        cxn44.a = "camera.logger_throttle_millis";
        j = cxn44.a();
        final cxn cxn45 = new cxn();
        cxn45.a = "max_allowed_allocator_memory_mb";
        k = cxn45.a();
        final cxn cxn46 = new cxn();
        cxn46.a = "max_allowed_native_memory_mb";
        l = cxn46.a();
        final cxn cxn47 = new cxn();
        cxn47.a = "measure_integration_enabled";
        an = cxn47.f();
        final cxn cxn48 = new cxn();
        cxn48.a = "ois_api_supported";
        ao = cxn48.f();
        final cxn cxn49 = new cxn();
        cxn49.a = "ois_api_version";
        m = cxn49.a();
        final cxn cxn50 = new cxn();
        cxn50.a = "camera.onscreen_logcat";
        ap = cxn50.b();
        final cxn cxn51 = new cxn();
        cxn51.a = "camera.onscreen_log";
        aq = cxn51.b();
        new cxn().a = "selfie_mirror_log";
        final cxn cxn52 = new cxn();
        cxn52.a = "p20_shutter_btn.enabled.RESTART";
        ar = cxn52.f();
        final cxn cxn53 = new cxn();
        cxn53.a = "p_or_higher";
        as = cxn53.f();
        final cxn cxn54 = new cxn();
        cxn54.a = "mn_enabled";
        at = cxn54.f();
        new cxn().a = "perfetto_trigger";
        final cxn cxn55 = new cxn();
        cxn55.a = "camera_perfetto_trigger_millis";
        cxn55.b = "General";
        n = cxn55.a();
        final cxn cxn56 = new cxn();
        cxn56.a = "camera.prod_testing";
        au = cxn56.f();
        final cxn cxn57 = new cxn();
        cxn57.a = "camera.progress_overlay";
        av = cxn57.c();
        new cxn().a = "mcfly_enabled";
        new cxn().a = "camera.enable_rocky";
        final cxn cxn58 = new cxn();
        cxn58.a = "camera.enable_zebras";
        aw = cxn58.f();
        final cxn cxn59 = new cxn();
        cxn59.a = "camera.zebras_others";
        ax = cxn59.f();
        new cxn().a = "fatal_error_sql_error_checks_enabled";
        final cxn cxn60 = new cxn();
        cxn60.a = "camera.shot_tracking";
        ay = cxn60.f();
        new cxn().a = "camera.shot_tracking.sql_checks";
        final cxn cxn61 = new cxn();
        cxn61.a = "camera.shot_tracking.stuck_age_seconds";
        o = cxn61.a();
        final cxn cxn62 = new cxn();
        cxn62.a = "pd_calibration_data_supported";
        az = cxn62.f();
        final cxn cxn63 = new cxn();
        cxn63.a = "camera.60fps";
        aA = cxn63.d();
        final cxn cxn64 = new cxn();
        cxn64.a = "unflipped_selfie_default";
        aB = cxn64.f();
        new cxn().a = "scripting_enabled";
        final cxn cxn65 = new cxn();
        cxn65.a = "camera_slow_launch_dialog_trigger_ms";
        cxn65.b = "General";
        p = cxn65.a();
        final cxn cxn66 = new cxn();
        cxn66.a = "enable_social_share";
        cxn66.b = "SocialShare";
        aC = cxn66.f();
        final cxn cxn67 = new cxn();
        cxn67.a = "social_share_v2_support_all_types";
        aD = cxn67.f();
        final cxn cxn68 = new cxn();
        cxn68.a = "enable_bounce_animation_on_social_share_menu";
        aE = cxn68.f();
        final cxn cxn69 = new cxn();
        cxn69.a = "camera.obfuscation_share_enabled";
        aF = cxn69.f();
        final cxn cxn70 = new cxn();
        cxn70.a = "squeeze_supported";
        aG = cxn70.f();
        new cxn().a = "camera.strict_vm";
        new cxn().a = "camera.strict_vm_die_on_violation";
        new cxn().a = "camera.strict_vm_visual_warning_on_violation";
        new cxn().a = "camera.strict_vm_diskread";
        new cxn().a = "camera.syshealth_info";
        new cxn().a = "camera.memory_monitor_overlay";
        final cxn cxn71 = new cxn();
        cxn71.a = "camera.double_tap_launch_bottom_sheet";
        q = cxn71.a();
        new cxn().a = "camera.dbg.bugtoast";
        final cxn cxn72 = new cxn();
        cxn72.a = "camera.skip_oobe";
        aH = cxn72.f();
        final cxn cxn73 = new cxn();
        cxn73.a = "camera.extra_zoom_linger";
        aI = cxn73.f();
        final cxn cxn74 = new cxn();
        cxn74.a = "camera.location_default";
        aJ = cxn74.f();
        new cxn().a = "camera.vfe.poc_gray";
        new cxn().a = "camera.vfe.debugbar";
        final cxn cxn75 = new cxn();
        cxn75.a = "camera.double_tap_launch_edu_enabled";
        aK = cxn75.f();
        final cxn cxn76 = new cxn();
        cxn76.a = "camera.auto_timer_enabled";
        aL = cxn76.f();
        new cxn().a = "use_pck_storage";
        final cxn cxn77 = new cxn();
        cxn77.a = "unflipped_selfie_enabled";
        aM = cxn77.f();
        final cxn cxn78 = new cxn();
        cxn78.a = "use_physical_raw";
        aN = cxn78.f();
        final cxn cxn79 = new cxn();
        cxn79.a = "camera.pck_large_yuv";
        aO = cxn79.f();
        new cxn().a = "use_minimal_q_storage_v2";
        final cxn cxn80 = new cxn();
        cxn80.a = "camera.no_media_type_none_on_q_or_above";
        aP = cxn80.f();
        final cxn cxn81 = new cxn();
        cxn81.a = "use_immersive_rounded_corners";
        aQ = cxn81.f();
        final cxn cxn82 = new cxn();
        cxn82.a = "camera.ddepth_rear";
        aR = cxn82.f();
        final cxn cxn83 = new cxn();
        cxn83.a = "camera.ddepth_front";
        aS = cxn83.f();
        new cxn().a = "camera.ddepth_debug";
        final cxn cxn84 = new cxn();
        cxn84.a = "camera.ddepth_preference_override";
        aT = cxn84.f();
        new cxn().a = "camera.ddepth_rear_use_opencl";
        new cxn().a = "camera.alloc_tracker";
        new cxn().a = "camera.mediafile_stuck_notification";
        new cxn().a = "camera.mediafile_stuck_crash";
        new cxn().a = "camera.custom_hotkeys";
        final cxn cxn85 = new cxn();
        cxn85.a = "camera.no_low_fb";
        aU = cxn85.f();
        new cxn().a = "camera.fb_hcheck";
        new cxn().a = "camera.log_frame_availability";
        final cxn cxn86 = new cxn();
        cxn86.a = "camera.allow_fine_haptics";
        aV = cxn86.f();
        new cxn().a = "camera.jankmonitor_full";
        final cxn cxn87 = new cxn();
        cxn87.a = "camera.sparrow";
        aW = cxn87.f();
        new cxn().a = "camera.crash_unknown_thermal_status";
        new cxn().a = "camera.dots_of_doom";
        final cxn cxn88 = new cxn();
        cxn88.b = "Beholder";
        cxn88.a = "beholder_enabled";
        aX = cxn88.f();
        final cxn cxn89 = new cxn();
        cxn89.b = "Beholder";
        cxn89.a = "beholder_example_sensor_buffer_size";
        r = cxn89.a();
        final cxn cxn90 = new cxn();
        cxn90.b = "Beholder";
        cxn90.a = "beholder_no_training_threshold";
        s = cxn90.a();
        final cxn cxn91 = new cxn();
        cxn91.b = "Beholder";
        cxn91.a = "beholder_population_name";
        aY = cxn91.g();
        final cxn cxn92 = new cxn();
        cxn92.b = "Beholder";
        cxn92.a = "beholder_suggestion_enabled";
        new cxn().a = "camera.ica_in_front_enabled";
        new cxn().a = "test_only_beholder_e2e";
        final cxn cxn93 = new cxn();
        cxn93.a = "beholder_save_frame";
        aZ = cxn93.f();
        new cxn().a = "test_only_beholder_enabled";
        new cxn().a = "camera.beholder_force_opt_in";
        new cxn().a = "camera.nga_direct_actions";
        new cxn().a = "camera.enable_guava_verbose_futures";
        new cxn().a = "camera.gl.log_caller_stacktrace";
        new cxn().a = "camera.gl.log_contexts";
        new cxn().a = "camera.gl.crash_if_exec_rejected";
        final cxn cxn94 = new cxn();
        cxn94.a = "camera.storage_space_override";
        t = cxn94.a();
        final cxn cxn95 = new cxn();
        cxn95.a = "camera.jpeg_data_rotation";
        ba = cxn95.f();
        new cxn().a = "camera.debug_lossless_image";
        final cxn cxn96 = new cxn();
        cxn96.a = "test_only_camera_device_disable";
        final Integer value = 0;
        final Integer value2 = 1;
        final Integer value3 = 2;
        final Integer value4 = 3;
        cxn96.c = noi.K(value, value2, value3, value4);
        u = cxn96.a();
        final cxn cxn97 = new cxn();
        cxn97.a = "test_only_camera_open_disable";
        cxn97.c = noi.K(value, value2, value3, value4);
        v = cxn97.a();
        final cxn cxn98 = new cxn();
        cxn98.a = "test_only_camera_id_rear";
        final Integer value5 = -1;
        final Integer value6 = 9;
        cxn98.c = nlv.a(nqe.f(value5, value6), nme.a);
        w = cxn98.a();
        final cxn cxn99 = new cxn();
        cxn99.a = "test_only_camera_id_front";
        cxn99.c = nlv.a(nqe.f(value5, value6), nme.a);
        x = cxn99.a();
        final cxn cxn100 = new cxn();
        cxn100.b = "HardwareHelp";
        cxn100.a = "open_duration_threshold_for_fallback_millis";
        y = cxn100.a();
        final cxn cxn101 = new cxn();
        cxn101.a = "test_only_open_duration_threshold_millis";
        z = cxn101.a();
        final cxn cxn102 = new cxn();
        cxn102.b = "HardwareHelp";
        cxn102.a = "device_help";
        bb = cxn102.f();
        final cxn cxn103 = new cxn();
        cxn103.b = "HardwareHelp";
        cxn103.a = "enumeration_failures_before_reboot_threshold";
        A = cxn103.a();
        final cxn cxn104 = new cxn();
        cxn104.b = "HardwareHelp";
        cxn104.a = "enumeration_failures_after_reboot_threshold";
        B = cxn104.a();
        final cxn cxn105 = new cxn();
        cxn105.b = "HardwareHelp";
        cxn105.a = "fatal_failures_before_reboot_threshold";
        C = cxn105.a();
        final cxn cxn106 = new cxn();
        cxn106.b = "HardwareHelp";
        cxn106.a = "fatal_failures_after_reboot_threshold";
        D = cxn106.a();
        final cxn cxn107 = new cxn();
        cxn107.a = "fatal_error_tracker_days_to_reset";
        cxn107.b = "General";
        E = cxn107.a();
        final cxn cxn108 = new cxn();
        cxn108.b = "HardwareHelp";
        cxn108.a = "working_camera_fallback_enabled";
        bc = cxn108.f();
        new cxn().a = "camera.share_preview_analysis";
        new cxn().a = "test_only_working_camera_fallback_enabled";
        final cxn cxn109 = new cxn();
        cxn109.b = "HardwareHelp";
        cxn109.a = "support_link";
        bd = cxn109.g();
        new cxn().a = "camera.naruto";
        new cxn().a = "camera.analysis.private";
        new cxn().a = "camera.viewfinder_effect_enabled_photo";
        final cxn cxn110 = new cxn();
        cxn110.a = "camera.viewfinder_effect_disabled_photo";
        be = cxn110.f();
        final cxn cxn111 = new cxn();
        cxn111.a = "camera.viewfinder_effect_disabled_night";
        bf = cxn111.f();
        new cxn().a = "camera.launch_vfe";
        new cxn().a = "camera.crash_on_invalid_meta_data_from_media_store";
        new cxn().a = "camera.mediastorage_crash_on_second_publish";
        final cxn cxn112 = new cxn();
        cxn112.a = "ideal_aov_rad";
        bg = cxn112.e();
        final cxn cxn113 = new cxn();
        cxn113.a = "support_viewfinder_double_tap";
        cxn113.b = "General";
        bh = cxn113.f();
        final cxn cxn114 = new cxn();
        cxn114.a = "enable_survey";
        cxn114.b = "Survey";
        new cxn().a = "camera.enable_dogfood_notifications";
        new cxn().a = "enable_countdown_indicator";
        final cxn cxn115 = new cxn();
        cxn115.a = "enable_mars";
        bi = cxn115.f();
        final cxn cxn116 = new cxn();
        cxn116.a = "enable_inapp_update";
        cxn116.b = "General";
        new cxn().a = "camera.topshotp";
        new cxn().a = "camera.topshotns";
        new cxn().a = "enable_face_obfuscation";
        new cxn().a = "camera.zoom.debug";
        final cxn cxn117 = new cxn();
        cxn117.a = "camera.zoom.initial_zoom";
        bj = cxn117.e();
        final cxn cxn118 = new cxn();
        cxn118.a = "enable_sideline";
        cxn118.b = "General";
    }
}
