// 
// Decompiled by Procyon v0.6.0
// 

public final class cxw
{
    public static final cxo a;
    public static final cxo b;
    public static final cxm c;
    public static final cxm d;
    public static final cxm e;
    public static final cxm f;
    public static final cxm g;
    public static final cxm h;
    public static final cxm i;
    public static final cxm j;
    public static final cxm k;
    public static final cxm l;
    public static final cxm m;
    public static final cxm n;
    public static final cxm o;
    public static final cxm p;
    public static final cxm q;
    public static final cxm r;
    public static final cxm s;
    public static final cxm t;
    public static final cxm u;
    public static final cxm v;
    public static final cxm w;
    public static final cxm x;
    public static final cxm y;
    
    static {
        new cxn().a = "camera.micro_datacoll";
        new cxn().a = "camera.enable_jpgcheck";
        new cxn().a = "camera.micro_cam_pose";
        new cxn().a = "camera.micro_creation";
        new cxn().a = "camera.micro_no_gyro";
        new cxn().a = "camera.enable_micro_he";
        new cxn().a = "camera.micro_longp_hires";
        final cxn cxn = new cxn();
        cxn.a = "camera.micro_longp_mp4";
        c = cxn.c();
        new cxn().a = "camera.micro_longp_lj";
        final cxn cxn2 = new cxn();
        cxn2.a = "camera.micro_longp_md";
        d = cxn2.f();
        new cxn().a = "camera.micro_longp_pre_audio";
        final cxn cxn3 = new cxn();
        cxn3.a = "camera.micro_motion";
        e = cxn3.c();
        new cxn().a = "camera.micro_profile";
        final cxn cxn4 = new cxn();
        cxn4.a = "camera.micro_tone_map";
        f = cxn4.d();
        final cxn cxn5 = new cxn();
        cxn5.a = "camera.micro_tooltip";
        g = cxn5.c();
        new cxn().a = "camera.micro_trimtoast";
        final cxn cxn6 = new cxn();
        cxn6.a = "camera.enable_micro";
        h = cxn6.f();
        final cxn cxn7 = new cxn();
        cxn7.a = "micro_video_supported";
        i = cxn7.f();
        final cxn cxn8 = new cxn();
        cxn8.a = "camera.micro_prestab";
        j = cxn8.f();
        final cxn cxn9 = new cxn();
        cxn9.a = "camera.micro_v2_format";
        k = cxn9.f();
        new cxn().a = "camera.micro_longp_v2";
        new cxn().a = "camera.mv_dump_yuv";
        new cxn().a = "camera.mv_verbose";
        final cxn cxn10 = new cxn();
        cxn10.a = "camera.micro_gcamux";
        l = cxn10.f();
        new cxn().a = "camera.micro_stab_locked";
        new cxn().a = "camera.micro_render_stab_mesh";
        final cxn cxn11 = new cxn();
        cxn11.a = "camera.micro_longp_slide";
        m = cxn11.f();
        final cxn cxn12 = new cxn();
        cxn12.a = "camera.longp_topshot_indicator";
        n = cxn12.f();
        final cxn cxn13 = new cxn();
        cxn13.a = "camera.longp_zoom_lock";
        o = cxn13.f();
        final cxn cxn14 = new cxn();
        cxn14.a = "camera.longp_top_shot_animation";
        a = cxn14.a();
        new cxn().a = "camera.micro_debug_trimmer";
        new cxn().a = "camera.micro_overlay_metrics";
        final cxn cxn15 = new cxn();
        cxn15.a = "camera.micro_bottom_sheet";
        p = cxn15.f();
        final cxn cxn16 = new cxn();
        cxn16.a = "camera.micro_ls_always_prestab";
        q = cxn16.f();
        final cxn cxn17 = new cxn();
        cxn17.a = "camera.micro_longp_help";
        r = cxn17.f();
        final cxn cxn18 = new cxn();
        cxn18.a = "camera.longp_topshot_notification";
        s = cxn18.f();
        new cxn().a = "camera.micro_dynamic_i";
        final cxn cxn19 = new cxn();
        cxn19.a = "camera.micro_newtrimmer";
        t = cxn19.f();
        final cxn cxn20 = new cxn();
        cxn20.a = "camera.micro_early_ls";
        u = cxn20.f();
        final cxn cxn21 = new cxn();
        cxn21.a = "camera.micro_ls_cancel";
        v = cxn21.f();
        final cxn cxn22 = new cxn();
        cxn22.a = "camera.r_pending_vids";
        w = cxn22.f();
        final cxn cxn23 = new cxn();
        cxn23.a = "camera.check_pending_vids";
        x = cxn23.f();
        final cxn cxn24 = new cxn();
        cxn24.a = "camera.micro_ls_cthreshold";
        b = cxn24.a();
        new cxn().a = "camera.ls_on_mash";
        final cxn cxn25 = new cxn();
        cxn25.a = "camera.mv_no_double_close";
        y = cxn25.f();
    }
    
    public static void a(final cxq cxq, final cyn cyn) {
        cyn.b(cyn.a);
        cxq.p(cxw.c);
        cxq.s(cxw.d, true);
        cxq.p(cxw.e);
        cxq.q(cxw.f, true);
        cxq.p(cxw.g);
        cxq.s(cxw.i, true);
        cxq.s(cxw.h, true);
        cxq.s(cxw.j, false);
        cxq.s(cxw.k, true);
        cxq.s(cxw.l, true);
        cxq.s(cxw.m, true);
        cxq.s(cxw.o, true);
        cxq.s(cxw.n, true);
        cxq.s(cxw.q, false);
        cxq.s(cxw.r, true);
        cxq.s(cxw.s, true);
        cxq.s(cxw.t, true);
        cxq.s(cxw.p, true);
        cxq.s(cxw.u, true);
        cxq.s(cxw.v, true);
        cxq.s(cxw.w, true);
        cxq.s(cxw.x, true);
        cxq.o(cxw.b, 800);
        cxq.o(cxw.a, 2);
        cxq.s(cxw.y, true);
    }
}
