// 
// Decompiled by Procyon v0.6.0
// 

public final class cxx
{
    public static final cxm A;
    public static final cxm B;
    public static final cxm C;
    public static final cxm D;
    public static final cxm E;
    public static final cxm F;
    public static final cxm G;
    public static final cxm H;
    public static final cxm I;
    public static final cxm J;
    public static final cxm K;
    public static final cxm L;
    public static final cxm M;
    public static final cxm N;
    public static final cxm O;
    public static final cxm P;
    public static final cxm a;
    public static final cxm b;
    public static final cxm c;
    public static final cxm d;
    public static final cxm e;
    public static final cxm f;
    public static final cxm g;
    public static final cxm h;
    public static final cxm i;
    public static final cxm j;
    public static final cxm k;
    public static final cxm l;
    public static final cxm m;
    public static final cxm n;
    public static final cxm o;
    public static final cxm p;
    public static final cxm q;
    public static final cxm r;
    public static final cxm s;
    public static final cxm t;
    public static final cxm u;
    public static final cxm v;
    public static final cxm w;
    public static final cxm x;
    public static final cxm y;
    public static final cxm z;
    
    static {
        final cxn cxn = new cxn();
        cxn.b = "Topshot";
        cxn.a = "camera_mts_aesthetic";
        a = cxn.f();
        final cxn cxn2 = new cxn();
        cxn2.b = "Topshot";
        cxn2.a = "camera_mts_actions_front";
        b = cxn2.f();
        final cxn cxn3 = new cxn();
        cxn3.b = "Topshot";
        cxn3.a = "camera_mts_actions_back";
        c = cxn3.f();
        final cxn cxn4 = new cxn();
        cxn4.b = "Topshot";
        cxn4.a = "camera_mts_face_interactions";
        d = cxn4.f();
        final cxn cxn5 = new cxn();
        cxn5.a = "camera.mts_accel_faces_front";
        e = cxn5.f();
        final cxn cxn6 = new cxn();
        cxn6.a = "camera.mts_accel_faces_back";
        f = cxn6.f();
        final cxn cxn7 = new cxn();
        cxn7.a = "camera.mts_accel_action_front";
        g = cxn7.f();
        final cxn cxn8 = new cxn();
        cxn8.a = "camera.mts_accel_action_back";
        h = cxn8.f();
        new cxn().a = "camera.mts_sc_accel_tpu";
        final cxn cxn9 = new cxn();
        cxn9.a = "camera.mts_4k";
        i = cxn9.f();
        final cxn cxn10 = new cxn();
        cxn10.a = "camera.mts_ls_dupe_last";
        j = cxn10.f();
        final cxn cxn11 = new cxn();
        cxn11.a = "camera.mts_ts_ls_dupe_last";
        k = cxn11.f();
        new cxn().a = "camera.mts_fc_extraction";
        new cxn().a = "camera.mts_smart_zoom";
        new cxn().a = "camera.mts_scoring_dbg";
        final cxn cxn12 = new cxn();
        cxn12.a = "camera.mts_postview";
        l = cxn12.c();
        final cxn cxn13 = new cxn();
        cxn13.a = "camera.mts_fast_hdr";
        m = cxn13.f();
        new cxn().a = "camera.mts_fast_de_ts";
        final cxn cxn14 = new cxn();
        cxn14.a = "camera.mts_fast_de_ls";
        n = cxn14.f();
        new cxn().a = "camera.mts_ts_de_d2x";
        final cxn cxn15 = new cxn();
        cxn15.a = "camera.mts_ls_de_d2x";
        o = cxn15.f();
        final cxn cxn16 = new cxn();
        cxn16.b = "Topshot";
        cxn16.a = "mts_ls_de_d2x";
        p = cxn16.f();
        new cxn().a = "camera.mts_alt_w_main";
        final cxn cxn17 = new cxn();
        cxn17.b = "Topshot";
        cxn17.a = "mts_max_alt_1";
        q = cxn17.f();
        final cxn cxn18 = new cxn();
        cxn18.a = "camera.mts_max_alt_1";
        r = cxn18.f();
        final cxn cxn19 = new cxn();
        cxn19.b = "Topshot";
        cxn19.a = "camera_mts_lowlight_or_zoom";
        s = cxn19.f();
        final cxn cxn20 = new cxn();
        cxn20.a = "camera.mts_postproc";
        t = cxn20.f();
        final cxn cxn21 = new cxn();
        cxn21.a = "camera.mts_gpu";
        u = cxn21.f();
        final cxn cxn22 = new cxn();
        cxn22.a = "camera.mts_hw_enc_w";
        v = cxn22.f();
        final cxn cxn23 = new cxn();
        cxn23.b = "Topshot";
        cxn23.a = "mts_face_diversity";
        w = cxn23.f();
        final cxn cxn24 = new cxn();
        cxn24.a = "camera.mts_face_diversity";
        x = cxn24.f();
        final cxn cxn25 = new cxn();
        cxn25.b = "Topshot";
        cxn25.a = "mts_aesthetic_diversity";
        y = cxn25.f();
        final cxn cxn26 = new cxn();
        cxn26.a = "camera.mts_aesthetic_diversity";
        z = cxn26.f();
        final cxn cxn27 = new cxn();
        cxn27.b = "Topshot";
        cxn27.a = "mts_long_shot_diversity";
        A = cxn27.f();
        final cxn cxn28 = new cxn();
        cxn28.a = "camera.mts_long_shot_diversity";
        B = cxn28.f();
        final cxn cxn29 = new cxn();
        cxn29.a = "camera.mts_nima_aesthetic_tpu";
        C = cxn29.f();
        final cxn cxn30 = new cxn();
        cxn30.a = "camera.mts_enable_nima_v2";
        D = cxn30.f();
        final cxn cxn31 = new cxn();
        cxn31.a = "camera.mts_motion_photo_threshold";
        E = cxn31.f();
        final cxn cxn32 = new cxn();
        cxn32.a = "camera.mts_durfix_ls";
        F = cxn32.f();
        final cxn cxn33 = new cxn();
        cxn33.a = "camera.mts_durfix_ts";
        G = cxn33.f();
        new cxn().a = "camera.mts_new_topshot_weight";
        final cxn cxn34 = new cxn();
        cxn34.a = "camera.mts_wait_ef";
        H = cxn34.f();
        new cxn().a = "camera.mts_full_res";
        new cxn().a = "camera.mts_full_br";
        final cxn cxn35 = new cxn();
        cxn35.a = "camera.mts_full_res_ls";
        I = cxn35.f();
        final cxn cxn36 = new cxn();
        cxn36.a = "camera.mts_full_br_ls";
        J = cxn36.f();
        new cxn().a = "camera.mts_full_color_range";
        final cxn cxn37 = new cxn();
        cxn37.a = "camera.mts_func_encoder";
        K = cxn37.f();
        final cxn cxn38 = new cxn();
        cxn38.a = "camera.mts_prewarm";
        L = cxn38.c();
        final cxn cxn39 = new cxn();
        cxn39.a = "camera.mts_gpu_yuv";
        M = cxn39.f();
        new cxn().a = "camera.mts_early_first_alt";
        final cxn cxn40 = new cxn();
        cxn40.a = "camera.mts_newscore";
        N = cxn40.f();
        final cxn cxn41 = new cxn();
        cxn41.a = "camera.longshot_xtra_frames";
        O = cxn41.f();
        final cxn cxn42 = new cxn();
        cxn42.a = "camera.longshot_lazy_proc";
        P = cxn42.f();
        new cxn().a = "camera.mts_direct_encode";
    }
}
