// 
// Decompiled by Procyon v0.6.0
// 

public final class cyc
{
    public static final cxm A;
    public static final cxm B;
    public static final cxm C;
    public static final cxo a;
    public static final cxo b;
    public static final cxo c;
    public static final cxo d;
    public static final cxo e;
    public static final cxm f;
    public static final cxm g;
    public static final cxm h;
    public static final cxm i;
    public static final cxm j;
    public static final cxm k;
    public static final cxm l;
    public static final cxm m;
    public static final cxm n;
    public static final cxm o;
    public static final cxm p;
    public static final cxm q;
    public static final cxm r;
    public static final cxm s;
    public static final cxm t;
    public static final cxm u;
    public static final cxm v;
    public static final cxm w;
    public static final cxm x;
    public static final cxm y;
    public static final cxm z;
    
    static {
        final cxn cxn = new cxn();
        cxn.a = "camera.gouda.depthdata";
        f = cxn.f();
        final cxn cxn2 = new cxn();
        cxn2.a = "gouda_default_zoom_factor_back";
        g = cxn2.e();
        final cxn cxn3 = new cxn();
        cxn3.a = "gouda_doubletap_zoom_factor";
        h = cxn3.e();
        new cxn().a = "gouda_use_default_zoom_factor_front_for_test";
        final cxn cxn4 = new cxn();
        cxn4.a = "gouda_default_zoom_factor_front_for_test";
        i = cxn4.e();
        final cxn cxn5 = new cxn();
        cxn5.a = "max_gouda_inflight_shots";
        a = cxn5.a();
        final cxn cxn6 = new cxn();
        cxn6.a = "portrait_availability";
        j = cxn6.f();
        final cxn cxn7 = new cxn();
        cxn7.a = "camera.gouda_debug_img";
        k = cxn7.f();
        final cxn cxn8 = new cxn();
        cxn8.a = "camera.gouda.raw";
        l = cxn8.f();
        final cxn cxn9 = new cxn();
        cxn9.a = "camera.gouda_sec_img";
        m = cxn9.f();
        final cxn cxn10 = new cxn();
        cxn10.a = "segmenter_force_cpu_inference";
        n = cxn10.f();
        final cxn cxn11 = new cxn();
        cxn11.a = "segmenter_allow_fp16_processing";
        o = cxn11.f();
        final cxn cxn12 = new cxn();
        cxn12.a = "segmenter_allow_texture_type";
        p = cxn12.f();
        final cxn cxn13 = new cxn();
        cxn13.a = "camera.gouda.cl_seg";
        q = cxn13.f();
        final cxn cxn14 = new cxn();
        cxn14.a = "segmenter_use_darwinn_tpu_delegate";
        r = cxn14.f();
        new cxn().a = "camera.gouda.matting_enabled";
        final cxn cxn15 = new cxn();
        cxn15.a = "camera.gouda.firefly_cpu";
        s = cxn15.f();
        final cxn cxn16 = new cxn();
        cxn16.a = "camera.gouda.depth_use_opencl";
        t = cxn16.f();
        final cxn cxn17 = new cxn();
        cxn17.a = "camera.gouda.stdepth";
        u = cxn17.f();
        final cxn cxn18 = new cxn();
        cxn18.a = "camera.gouda.primary_raw";
        v = cxn18.f();
        final cxn cxn19 = new cxn();
        cxn19.a = "camera.gouda.allow_raw_blur_front";
        w = cxn19.f();
        final cxn cxn20 = new cxn();
        cxn20.a = "camera.gouda.allow_raw_blur_rear";
        x = cxn20.f();
        final cxn cxn21 = new cxn();
        cxn21.a = "camera.gouda.use_dynamic_depth";
        y = cxn21.f();
        final cxn cxn22 = new cxn();
        cxn22.a = "camera.gouda.firefly_enabled";
        z = cxn22.f();
        final cxn cxn23 = new cxn();
        cxn23.a = "camera.gouda.shasta_zsl";
        A = cxn23.f();
        final cxn cxn24 = new cxn();
        cxn24.a = "camera.gouda.spotlight_enhance";
        B = cxn24.f();
        final cxn cxn25 = new cxn();
        cxn25.a = "camera.gouda.single_output";
        C = cxn25.f();
        final cxn cxn26 = new cxn();
        cxn26.a = "portrait_power_boost_duration_ms";
        b = cxn26.a();
        final cxn cxn27 = new cxn();
        cxn27.a = "camera.gouda.secondary_raw_width";
        c = cxn27.a();
        final cxn cxn28 = new cxn();
        cxn28.a = "camera.gouda.secondary_raw_height";
        d = cxn28.a();
        final cxn cxn29 = new cxn();
        cxn29.a = "camera.gouda.secondary_row_start";
        e = cxn29.a();
    }
}
