import com.google.android.apps.camera.ui.views.MainActivityLayout;
import com.google.android.apps.camera.ui.layout.GcaLayout;
import java.util.concurrent.atomic.AtomicReference;
import java.util.List;

// 
// Decompiled by Procyon v0.6.0
// 

public final class elr implements ejt
{
    public pii A;
    public pii B;
    public pii C;
    public pii D;
    public pii E;
    public pii F;
    public pii G;
    public pii H;
    public pii I;
    public pii J;
    public pii K;
    public pii L;
    public pii M;
    public pii N;
    public pii O;
    public pii P;
    public pii Q;
    public pii R;
    public pii S;
    public pii T;
    public pii U;
    public pii V;
    public pii W;
    public pii X;
    public pii Y;
    public pii Z;
    public final efs a;
    public final pii aA;
    public final pii aB;
    public final pii aC;
    public final pii aD;
    public final pii aE;
    public final pii aF;
    public final pii aG;
    public final pii aH;
    public final pii aI;
    public final pii aJ;
    public final pii aK;
    public final pii aL;
    public final pii aM;
    public final pii aN;
    public final pii aO;
    public final pii aP;
    public final pii aQ;
    public final pii aR;
    public final pii aS;
    public final pii aT;
    public final pii aU;
    public final pii aV;
    public final pii aW;
    public final pii aX;
    public final pii aY;
    public final pii aZ;
    public pii aa;
    public pii ab;
    public pii ac;
    public pii ad;
    public final pii ae;
    public final pii af;
    public final pii ag;
    public final pii ah;
    public final pii ai;
    public final pii aj;
    public final pii ak;
    public final pii al;
    public final pii am;
    public final pii an;
    public final pii ao;
    public final pii ap;
    public final pii aq;
    public final pii ar;
    public final pii as;
    public final pii at;
    public final pii au;
    public final pii av;
    public final pii aw;
    public final pii ax;
    public final pii ay;
    public final pii az;
    public final emf b;
    private pii bA;
    private pii bB;
    private pii bC;
    private pii bD;
    private pii bE;
    private pii bF;
    private pii bG;
    private pii bH;
    private pii bI;
    private pii bJ;
    private pii bK;
    private pii bL;
    private pii bM;
    private pii bN;
    private pii bO;
    private pii bP;
    private pii bQ;
    private pii bR;
    private pii bS;
    private pii bT;
    private pii bU;
    private pii bV;
    private pii bW;
    private pii bX;
    private pii bY;
    private pii bZ;
    public final pii ba;
    public final pii bb;
    public final pii bc;
    public final pii bd;
    public final pii be;
    public final pii bf;
    public final pii bg;
    public final pii bh;
    private final ejn bi;
    private pii bj;
    private pii bk;
    private pii bl;
    private pii bm;
    private pii bn;
    private pii bo;
    private pii bp;
    private pii bq;
    private pii br;
    private pii bs;
    private pii bt;
    private pii bu;
    private pii bv;
    private pii bw;
    private pii bx;
    private pii by;
    private pii bz;
    public final elr c;
    private final pii cA;
    private final pii cB;
    private final pii cC;
    private final pii cD;
    private final pii cE;
    private final pii cF;
    private final pii cG;
    private final pii cH;
    private final pii cI;
    private final pii cJ;
    private final pii cK;
    private final pii cL;
    private final pii cM;
    private final pii cN;
    private final pii cO;
    private final pii cP;
    private final pii cQ;
    private final pii cR;
    private final pii cS;
    private final pii cT;
    private final pii cU;
    private final pii cV;
    private final pii cW;
    private final pii cX;
    private final pii cY;
    private final pii cZ;
    private pii ca;
    private pii cb;
    private pii cc;
    private pii cd;
    private final pii ce;
    private final pii cf;
    private final pii cg;
    private final pii ch;
    private final pii ci;
    private final pii cj;
    private final pii ck;
    private final pii cl;
    private final pii cm;
    private final pii cn;
    private final pii co;
    private final pii cp;
    private final pii cq;
    private final pii cr;
    private final pii cs;
    private final pii ct;
    private final pii cu;
    private final pii cv;
    private final pii cw;
    private final pii cx;
    private final pii cy;
    private final pii cz;
    public pii d;
    private final pii da;
    private final pii db;
    private final pii dc;
    private final pii dd;
    private final pii de;
    private final pii df;
    private final pii dg;
    private final pii dh;
    private final pii di;
    private final pii dj;
    private final pii dk;
    private final pii dl;
    private final pii dm;
    private final pii dn;
    private final pii do;
    public pii e;
    public pii f;
    public pii g;
    public pii h;
    public pii i;
    public pii j;
    public pii k;
    public pii l;
    public pii m;
    public pii n;
    public pii o;
    public pii p;
    public pii q;
    public pii r;
    public pii s;
    public pii t;
    public pii u;
    public pii v;
    public pii w;
    public pii x;
    public pii y;
    public pii z;
    
    public elr(final emf b, final ejn bi, final efs a, final hus hus) {
        this.c = this;
        this.b = b;
        this.d(this.bi = bi, this.a = a, hus);
        final itl ce = new itl(b.x, b.ds);
        this.ce = ce;
        final pii b2 = oum.b(new erq(b.dr, this.cd, ce));
        this.cf = b2;
        final itt cg = new itt(b.B, this.g, this.Q, b2, b.x, b.A, this.d, b.bM);
        this.cg = cg;
        this.ae = oum.b(new diw(cg, b.B, this.r, this.h, 20, null, null));
        this.af = oum.b(ihm.a);
        this.ag = new egl(b.g, 10);
        final pii b3 = oum.b(gjk.a);
        this.ah = b3;
        this.ai = new guv(this.j, b.as, this.R, 20, (float[][])null);
        this.aj = oum.b(new grt(b.j, 14));
        final pii b4 = oum.b(new hzw(this.m, 18));
        this.ak = b4;
        this.al = oum.b(jgj.a);
        this.am = oum.b(jgh.a);
        final pii b5 = oum.b(hlv.a);
        this.an = b5;
        this.ao = new hkb(b5, b.ag, 13, (char[][])null);
        final jbu b6 = jbu.b(this.t);
        this.ch = b6;
        final pii b7 = oum.b(new bxh(b6, b4, b.Z, this.p, this.r, b.j, b.aa));
        this.ap = b7;
        this.aq = new dzg(7);
        final pii b8 = oum.b(hlw.a);
        this.ar = b8;
        this.as = oum.b(new hkr(b8, 20));
        final pii b9 = oum.b(new ied(b.B, b.j, this.j, 9, (byte[][])null));
        this.at = b9;
        final pii b10 = oum.b(ind.a);
        this.ci = b10;
        final pii b11 = oum.b(new iki(this.m, b.j, b.B, b10, 2, (byte[])null));
        this.au = b11;
        this.av = oum.b(new iki(this.m, b11, b.as, b.j, 3, (char[])null));
        final hxe cj = new hxe(this.j);
        this.cj = cj;
        this.aw = oum.b(new hpi(cj, 7));
        final hxv ck = new hxv(b.cM, b.db, b.cV, b.cU, b.cT, b.as);
        this.ck = ck;
        final pii b12 = oum.b(new hok(this.j, this.f, this.R, ck, b.N, b.B, this.h, 2, null));
        this.ax = b12;
        final pii c = emd.c(b.bc);
        this.cl = c;
        final pii b13 = oum.b(cuy.a);
        this.cm = b13;
        final pii c2 = emd.c(b.aX);
        this.cn = c2;
        final pii b14 = oum.b(new cbk(b.en, b.j, 19, (byte[][])null));
        this.co = b14;
        final pii b15 = oum.b(new bnj(c2, b14, this.t, this.f, b.br, b.N, 12, (boolean[][])null));
        this.ay = b15;
        final pii b16 = oum.b(new cbl(b.j, 10));
        this.cp = b16;
        final pii b17 = oum.b(new bnj(c, b16, this.t, this.f, b.br, b.N, 13, (float[][])null));
        this.az = b17;
        final pii b18 = oum.b(new cik(c, b13, this.t, this.f, b.br, b.j, b15, b.en, b17, b.N, 3, (char[])null));
        this.aA = b18;
        final pii b19 = oum.b(new bks(b.h, 4));
        this.cq = b19;
        final pii b20 = oum.b(bqk.a);
        this.aB = b20;
        this.aC = oum.b(new bqj(b19, b.aJ, b.Y, b.bX, b.aG, b.ep, b20, this.r));
        this.aD = oum.b(ckw.a);
        this.aE = oum.b(fng.a);
        final inz af = new inz(this.bj);
        this.aF = af;
        this.aG = oum.b(cqo.a);
        final pii a2 = out.a(hkh.a(b.i, jdw.a));
        this.cr = a2;
        final bxo cs = new bxo(b.j);
        this.cs = cs;
        final pii b21 = oum.b(new cdf(b.j, b.B, this.n, b.dl, b.r, this.bM, b.as, b.q, this.u, b.dH, b7, b.s, b.bf, b.bD, b.bh, c2, c, b.fb, b.fc, b.fd, b.fe, cs, b.H, 1));
        this.ct = b21;
        final cbk cu = new cbk(this.bL, b21, 1);
        this.cu = cu;
        final oun a3 = ous.a;
        final List j = pjv.j(0);
        final List i = pjv.j(1);
        pqf.h(cu, i);
        final ous g = pqf.g(j, i);
        this.cv = g;
        final bxr cw = new bxr(b.I, g);
        this.cw = cw;
        final pii b22 = oum.b(new dxo(b.cg, this.aa, b.br, b.dw, a2, cw, 4, (short[])null));
        this.aH = b22;
        this.aI = oum.b(new ezm(this.t, b4, 13, (float[])null));
        this.aJ = oum.b(new bks(this.bp, 17));
        this.aK = oum.b(new dzb(this.j, 17));
        final pii b23 = oum.b(new erq(b.dN, this.f, b.j, 7, (float[])null));
        this.cx = b23;
        final pii c3 = emd.c(b23);
        this.cy = c3;
        this.aL = new ezm(c3, b.ag, 6);
        final pii b24 = oum.b(new cbp(b.en, b.N, b.j, 7, (float[])null));
        this.cz = b24;
        final pii b25 = oum.b(new bxh(b24, this.j, this.R, c2, b.N, b.br, b.j, 7, (float[])null));
        this.aM = b25;
        this.aN = oum.b(new ihz(b.h, b.ax, 6, (int[])null));
        this.aO = oum.b(new bks(this.bp, 19));
        this.aP = oum.b(new bks(this.bp, 16));
        final igx b26 = igx.b(b.ct);
        this.cA = b26;
        final pii b27 = oum.b(new hok(b.B, b.N, b26, b.dD, this.Y, af, b.j));
        this.cB = b27;
        final pii b28 = oum.b(new gts(this.j, b.I, b.N, b27, b.dD, this.S, this.aa, this.Y, 5, (int[])null));
        this.aQ = b28;
        final hlx cc = new hlx(b3, b10, this.q, this.j);
        this.cC = cc;
        final pii b29 = oum.b(new gtm(b.fs, b27, b28, this.L, b.dl, b.eF, b.cq, this.f, cc, b.o, 4, (short[])null));
        this.aR = b29;
        this.aS = new guv(b29, b.B, this.h, 12, (boolean[])null);
        this.aT = new bjp(this.bW, this.e, 3, (char[])null);
        final pii b30 = oum.b(new bmn(5));
        this.cD = b30;
        final bpx ce2 = new bpx(b.h, b30);
        this.cE = ce2;
        final pii b31 = oum.b(new bjp(ce2, b.j, 8));
        this.cF = b31;
        final dfc cg2 = new dfc(b.h);
        this.cG = cg2;
        final dfh ch = new dfh(this.j, this.f, b30, this.S, b.N, b.M, b.j);
        this.cH = ch;
        final pii b32 = oum.b(new bvv(cg2, ch, this.f, b.M, b.I, 10, (short[][])null));
        this.cI = b32;
        final dfi cj2 = new dfi(b32, b.j, this.r);
        this.cJ = cj2;
        this.aU = new bkd(b31, cj2, this.n, b.B, 19, (float[][][])null);
        final pii b33 = oum.b(new hpi(b5, 1));
        this.cK = b33;
        this.aV = new bji(this.bL, b33, b21, 14, (float[][])null);
        final bmi cl = new bmi(b.j, 2);
        this.cL = cl;
        final pii b34 = oum.b(new ezm(b.cg, this.aa));
        this.cM = b34;
        final ezm cn = new ezm(cl, b34, 2);
        this.cN = cn;
        final pii b35 = oum.b(new gsl(b.cg, this.aa, 8, (int[])null));
        this.cO = b35;
        final guv cp = new guv(b.j, cl, b35);
        this.cP = cp;
        final List k = pjv.j(0);
        final List l = pjv.j(2);
        pqf.h(cn, l);
        pqf.h(cp, l);
        final ous g2 = pqf.g(k, l);
        this.cQ = g2;
        final bxq cr = new bxq(b.I, g2);
        this.cR = cr;
        final pii b36 = oum.b(new bji(b.j, c2, cr, 19, (int[][][])null));
        this.cS = b36;
        this.aW = new bji(cl, b33, b36, 16);
        final bmi ct = new bmi(b.j, 4);
        this.cT = ct;
        final bmi cu2 = new bmi(b.j, 5);
        this.cU = cu2;
        final bkd cv = new bkd(this.bL, cl, b21, b36, 8, (byte[][])null);
        this.cV = cv;
        final List m = pjv.j(0);
        final List j2 = pjv.j(1);
        pqf.h(cv, j2);
        final ous g3 = pqf.g(m, j2);
        this.cW = g3;
        final cuo cx = new cuo(b.I, g3);
        this.cX = cx;
        final pii b37 = oum.b(new dmj(b.cg, this.aa, cw, 11, (short[][])null));
        this.cY = b37;
        final dyf cz = new dyf(b.j, b37, 10, (byte[][])null);
        this.cZ = cz;
        final pii b38 = oum.b(new huu(b.cg, this.aa, 18));
        this.da = b38;
        final huu db = new huu(b.j, b38, 16, (boolean[])null);
        this.db = db;
        final List j3 = pjv.j(0);
        final List j4 = pjv.j(2);
        pqf.h(cz, j4);
        pqf.h(db, j4);
        final ous g4 = pqf.g(j3, j4);
        this.dc = g4;
        final cup dd = new cup(b.I, g4);
        this.dd = dd;
        final evo de = new evo(b.j, this.S);
        this.de = de;
        final pii b39 = oum.b(new hkb(b.fs, b.fA, 15));
        this.df = b39;
        final evq dg = new evq(b.h);
        this.dg = dg;
        final eul dh = new eul(b.fB);
        this.dh = dh;
        final eun di = new eun(dh, b.N);
        this.di = di;
        final pii b40 = oum.b(new evl(b.h, this.r, b.fy, b.j, this.j, ct, cu2, cx, dd, this.S, de, this.R, b.N, this.aa, b.I, b39, b.B, dg, di));
        this.dj = b40;
        final euj dk = new euj(b.I, b.j, b.fC);
        this.dk = dk;
        this.aX = new dxo(b.j, b33, b40, b.bO, dk, this.r, 3, (char[])null);
        final pii b41 = oum.b(new bxh(b.cg, b.h, b.as, this.aa, b.j, b.br, cw, 11, (int[][])null));
        this.dl = b41;
        final pii b42 = oum.b(new fel(b.cg, this.aa, b.as, b9, 1));
        this.dm = b42;
        this.aY = new cik(b33, b22, b41, b34, b42, b.j, cl, b.eF, this.f, this.r, 6, (boolean[])null);
        final pii b43 = oum.b(new ffj(b.cg, this.aa, b.bC, b.br, cw, 19, (float[][][])null));
        this.dn = b43;
        this.aZ = new ffj(b.j, b33, cl, b43, b35, 17, (int[][][])null);
        this.ba = oum.b(new huu(b.B, this.u));
        this.bb = new bkd(this.r, b.dC, this.p, b.fD, 3, (char[])null);
        this.bc = new bxh(b.j, b.dp, b33, b15, b17, b25, b18, 6, (boolean[])null);
        this.bd = new dmj(b.j, b33, b37, 12, (int[][])null);
        this.be = new huu(b33, b12, 12, (short[])null);
        this.bf = new ied(b.j, b33, b38, 1);
        final pii b44 = oum.b(new ihz(this.j, b.B, 5, (short[])null));
        this.do = b44;
        this.bg = new ied(this.h, b.B, b44, 8, (float[])null);
        this.bh = oum.b(new bnj(b.h, b.j, this.h, this.L, this.bq, b.o, 3, (char[])null));
    }
    
    private final njp c() {
        return inz.b((AtomicReference)this.bj.get());
    }
    
    private final void d(final ejn ejn, final efs efs, final hus hus) {
        this.bj = oum.b(iny.a);
        final efy b = efy.b(efs);
        this.d = b;
        final jbl e = new jbl(b);
        this.e = e;
        this.f = oum.b(new iyb(e, 9));
        this.g = new efw(efs);
        this.bk = new hyx(this.b.B, this.g);
        this.h = ejs.a(ejn);
        this.i = oum.b(new hzl(this.bk, this.b.B, this.h, 1));
        this.j = eft.b(efs);
        final efz a = efz.a(efs);
        this.k = a;
        this.l = oum.b(bjp.b(a, this.b.B));
        final efu b2 = efu.b(efs);
        this.m = b2;
        final pii j = this.j;
        final pii l = this.l;
        final emf b3 = this.b;
        this.bl = oum.b(bnj.c(j, l, b2, b3.N, b3.D, b3.ap));
        this.n = ejo.a(ejn);
        this.bm = oum.b(cbp.a(this.b.B, this.n, this.m));
        final emf b4 = this.b;
        this.o = oum.b(bnj.d(b4.B, b4.bq, this.bl, b4.ap, b4.D, this.bm));
        final pii i = this.j;
        final pii k = this.l;
        final pii m = this.m;
        final emf b5 = this.b;
        final pii b6 = oum.b(bnj.b(i, k, m, b5.N, b5.D, b5.ap));
        this.bn = b6;
        final emf b7 = this.b;
        this.bo = oum.b(bxh.a(b6, b7.B, b7.bq, b7.ap, b7.N, b7.D, this.bm));
        final emf b8 = this.b;
        this.p = oum.b(bqj.a(b8.Z, b8.B, this.o, this.bo, b8.bq, b8.ap, b8.aH, this.d));
        this.q = new efx(efs);
        this.r = ejp.a(ejn);
        final emf b9 = this.b;
        final pii b10 = oum.b(bji.b(b9.x, b9.n, this.r));
        this.bp = b10;
        this.s = oum.b(bjp.d(b10, this.b.y));
        this.bq = oum.b(bjp.c(this.b.bs, this.s));
        final pii m2 = this.m;
        final emf b11 = this.b;
        this.br = new gla(m2, b11.bb, this.q, b11.M, this.r, this.bq, b11.o);
        this.t = oum.b(new fyp(this.h, this.b.B, this.br, 8, (boolean[])null));
        final pii k2 = this.k;
        final emf b12 = this.b;
        this.bs = new dfq(k2, b12.N, b12.A, this.f, b12.ap);
        this.bt = oum.b(new cbp(this.b.aH, this.r, this.bs, 12, (int[][])null));
        this.u = oum.b(new hut(hus));
        final emf b13 = this.b;
        this.bu = oum.b(new bnj(b13.ar, this.bo, this.u, b13.ap, b13.aH, b13.I));
        final bks bv = new bks(this.m, 2);
        this.bv = bv;
        this.bw = oum.b(bv);
        this.v = ejr.a(ejn);
        this.w = oum.b(gsl.g(this.m, this.b.bw));
        final pii m3 = this.m;
        final pii l2 = this.l;
        final pii h = this.h;
        final emf b14 = this.b;
        final cpb bx = new cpb(m3, l2, h, b14.bv, this.bw, this.v, b14.B, b14.bs, this.w, 1);
        this.bx = bx;
        final pii b15 = oum.b(bx);
        this.x = b15;
        this.by = oum.b(new bjp(b15, this.u, 4));
        final emf b16 = this.b;
        this.y = oum.b(new guv(b16.B, b16.j, this.f, 6, (char[])null));
        this.z = oum.b(new dzb(this.q, 16));
        final emf b17 = this.b;
        final ejv bz = new ejv(b17.B, b17.y, this.y, b17.bx, b17.by, b17.Z, this.z, this.u, b17.bz, this.p, b17.aJ, 4, (short[])null);
        this.bz = bz;
        this.A = oum.b(bz);
        final emf b18 = this.b;
        this.B = new eqz(b18.bA, b18.o);
        final oun a2 = ous.a;
        final List j2 = pjv.j(0);
        final List j3 = pjv.j(1);
        pqf.h(this.b.bS, j3);
        this.C = pqf.g(j2, j3);
        final List j4 = pjv.j(0);
        final List j5 = pjv.j(5);
        pqf.h(this.b.bF, j5);
        pqf.h(this.b.bL, j5);
        pqf.h(this.b.bP, j5);
        pqf.h(this.b.bR, j5);
        pqf.h(this.C, j5);
        this.bA = pqf.g(j4, j5);
        final emf b19 = this.b;
        final ifk bb = new ifk(b19.j, b19.o, b19.bT, this.u, this.p, 5, (int[])null);
        this.bB = bb;
        final pii b20 = oum.b(bb);
        this.D = b20;
        final eol b21 = eol.b(this.bA, b20, this.b.j);
        this.bC = b21;
        this.E = oum.b(new dmj(this.A, this.B, b21, 16));
        final emf b22 = this.b;
        this.F = hlc.b(b22.l, b22.Z, b22.j);
        final pii q = this.q;
        final emf b23 = this.b;
        this.bD = new ixb(q, b23.j, b23.bU);
        final pii q2 = this.q;
        final emf b24 = this.b;
        this.bE = new ixd(q2, b24.j, b24.Y, b24.bU);
        this.G = oum.b(new ied(this.b.j, this.bD, this.bE, 11, (short[][])null));
        final emf b25 = this.b;
        final flt bf = new flt(b25.Z, this.F, this.G, b25.o);
        this.bF = bf;
        this.H = new fmc(bf, this.b.M);
        final emf b26 = this.b;
        this.bG = oum.b(new fel(b26.Z, this.d, b26.aa, b26.j, 10, (short[][])null));
        final pii b27 = oum.b(ixo.a);
        this.I = b27;
        final pii b28 = oum.b(new fyp(this.H, this.bG, b27, 1));
        this.bH = b28;
        this.bI = oum.b(new dyf(this.E, b28, 18, (char[][][])null));
        final pii b29 = oum.b(new erq(this.A, this.B, this.bC, 1));
        this.J = b29;
        final dyf bj = new dyf(b29, this.bH, 17, (byte[][][])null);
        this.bJ = bj;
        final pii e2 = this.e;
        final pii bi = this.bI;
        final emf b30 = this.b;
        this.bK = oum.b(new bvv(e2, bi, bj, b30.bV, b30.o, 20, null, null));
        this.bL = new bmi(this.b.j, 3);
        this.bM = new bxs(this.j);
        this.bN = new bxp(this.b.j);
        final pii j6 = this.j;
        final emf b31 = this.b;
        this.bO = new bzy(j6, b31.p, b31.j, this.bM, b31.bW, b31.B, this.n, this.bN);
        final pii j7 = this.j;
        final emf b32 = this.b;
        final caa bp = new caa(j7, b32.p, b32.B, this.n, this.bN, b32.r);
        this.bP = bp;
        this.bQ = oum.b(new bji(this.bL, this.bO, bp, 15, (byte[][][])null));
        this.bR = new diw(this.f, this.b.bE, this.p, this.r, 3, (char[])null);
        this.K = new ejq(ejn);
        this.bS = oum.b(new hpi(this.u, 3));
        this.L = oum.b(new bks(this.s, 18));
        final emf b33 = this.b;
        this.bT = new hjs(b33.i, b33.as);
        final emf b34 = this.b;
        final pii h2 = b34.h;
        final pii k3 = this.K;
        final pii n = b34.N;
        final pii u = this.u;
        final pii bx2 = b34.bX;
        final pii bs = this.bS;
        final pii l3 = this.L;
        final emf b35 = this.b;
        this.M = oum.b(new cef(h2, k3, n, u, bx2, bs, l3, b35.o, this.f, b35.bY, this.t, this.bT, b35.bZ, 1));
        this.bU = new bji(this.b.B, this.h, this.M, 3, (char[])null);
        final emf b36 = this.b;
        final hgh bv2 = new hgh(b36.cb, b36.o, b36.B, this.n, b36.as, 6, (boolean[])null);
        this.bV = bv2;
        final pii b37 = oum.b(bv2);
        this.N = b37;
        final pii b38 = oum.b(new hkb(b37, this.b.o, 17));
        this.bW = b38;
        this.bX = new bjp(b38, this.e, 2, (byte[])null);
        final pii f = this.f;
        final emf b39 = this.b;
        this.bY = new bnj(f, b39.cc, b39.bH, b39.bK, b39.cd, b39.cf, 15, (char[][][])null);
        this.bZ = oum.b(new guv(this.j, this.l, this.b.M, 5));
        this.ca = oum.b(new grj(this.b.B, this.m, this.h, this.bZ, 13, (boolean[][])null));
        final List j8 = pjv.j(6);
        final List j9 = pjv.j(0);
        pqf.i(this.bQ, j8);
        pqf.i(this.bR, j8);
        pqf.i(this.bU, j8);
        pqf.i(this.bX, j8);
        pqf.i(this.bY, j8);
        pqf.i(this.ca, j8);
        this.cb = pqf.g(j8, j9);
        this.O = new kkh(this.b.B);
        final emf b40 = this.b;
        this.P = oum.b(new ejv(b40.at, this.bt, this.bu, this.by, this.bK, this.cb, b40.bs, this.s, b40.M, this.O, b40.o));
        final emf b41 = this.b;
        final hlk b42 = hlk.b(b41.cg, b41.as);
        this.cc = b42;
        final pii h3 = this.h;
        final pii j10 = this.j;
        final emf b43 = this.b;
        final pii b44 = oum.b(cef.a(h3, j10, b42, b43.ch, b43.ci, b43.cj, b43.ck, b43.cl, b43.cm, b43.j, b43.N, b43.B, b43.J));
        this.Q = b44;
        this.R = oum.b(dxo.b(this.v, this.j, this.m, b44, this.w, this.b.as));
        final pii j11 = this.j;
        final pii m4 = this.m;
        final emf b45 = this.b;
        this.S = oum.b(iih.a(j11, m4, b45.B, this.bq, b45.o, b45.j, this.R));
        final emf b46 = this.b;
        this.T = cko.b(b46.as, b46.cn, b46.j);
        final pii m5 = this.m;
        final pii v = this.v;
        final emf b47 = this.b;
        this.U = isc.b(m5, v, b47.Z, this.F, b47.as, this.T, b47.ca, this.cc, this.p);
        this.V = new efv(efs);
        this.W = new efv(efs, 1);
        this.X = new efv(efs, 2);
        this.Y = oum.b(new ihz(this.j, this.b.j, 18, (byte[][])null));
        this.Z = new hzw(this.b.j, 19);
        this.aa = oum.b(fln.a);
        this.ab = oum.b(new buh(7));
        final pii r = this.r;
        final emf b48 = this.b;
        this.ac = oum.b(new bji(r, b48.do, b48.B, 13, (boolean[][])null));
        this.ad = oum.b(new bjp(this.b.N, this.ab, 20));
        this.cd = new itj(this.b.aI);
    }
    
    @Override
    public final void a(final GcaLayout gcaLayout) {
        gcaLayout.d = this.c();
    }
    
    @Override
    public final void b(final MainActivityLayout mainActivityLayout) {
        mainActivityLayout.d = this.c();
        mainActivityLayout.q = (AtomicReference)this.bj.get();
        mainActivityLayout.r = (klv)this.f.get();
        mainActivityLayout.s = (hyt)this.i.get();
        mainActivityLayout.t = (cxl)this.b.j.get();
        mainActivityLayout.y = ejo.c(this.bi);
        mainActivityLayout.u = (cse)this.p.get();
        mainActivityLayout.v = (gkw)this.t.get();
        mainActivityLayout.x = (lae)this.b.bu.get();
        mainActivityLayout.w = (liz)this.b.f.get();
    }
}
