import java.util.Set;
import java.util.concurrent.Executor;
import java.util.List;

// 
// Decompiled by Procyon v0.6.0
// 

public final class elw implements cjx
{
    private final pii A;
    private final pii B;
    private final pii C;
    private final pii D;
    private final pii E;
    private final pii F;
    private final pii G;
    private final pii H;
    private final pii I;
    private final pii J;
    private final pii K;
    private final pii L;
    private final pii M;
    private final pii N;
    private final pii O;
    private final pii P;
    private final pii Q;
    private final pii R;
    private final pii S;
    private final pii T;
    private final pii U;
    private final pii V;
    private final pii W;
    private final pii X;
    private final pii Y;
    private final pii Z;
    private final cjy a;
    private final pii aa;
    private final pii ab;
    private final pii ac;
    private final pii ad;
    private final pii ae;
    private final pii af;
    private final emf b;
    private final pii c;
    private final pii d;
    private final pii e;
    private final pii f;
    private final pii g;
    private final pii h;
    private final pii i;
    private final pii j;
    private final pii k;
    private final pii l;
    private final pii m;
    private final pii n;
    private final pii o;
    private final pii p;
    private final pii q;
    private final pii r;
    private final pii s;
    private final pii t;
    private final pii u;
    private final pii v;
    private final pii w;
    private final pii x;
    private final pii y;
    private final pii z;
    
    public elw(final emf b, final cjq cjq, final cjy a) {
        this.b = b;
        this.a = a;
        oum.b(ckd.a);
        final oun a2 = ous.a;
        final List j = pjv.j(1);
        final List i = pjv.j(0);
        pqf.i(b.aL, j);
        final ous g = pqf.g(j, i);
        this.c = g;
        final pii b2 = oum.b(dbt.e(b.aK, g));
        this.d = b2;
        final pii b3 = oum.b(gdr.a);
        this.e = b3;
        this.f = oum.b(fyj.d(b.I, b3));
        final cjt g2 = new cjt(cjq);
        this.g = g2;
        final cjr h = new cjr(cjq);
        this.h = h;
        final pii b4 = oum.b(h);
        this.i = b4;
        final pii b5 = oum.b(dbt.d(g2, b4));
        this.j = b5;
        final dnf a3 = dnf.a(b.j, b2);
        this.k = a3;
        final pii b6 = oum.b(gdm.a);
        this.l = b6;
        final fyh n = fyh.n(b6);
        this.m = n;
        final cka n2 = new cka(a, b.Z, b.j);
        this.n = n2;
        final pii b7 = oum.b(dnf.j(n2, b.j));
        this.o = b7;
        final cnp p3 = new cnp(g2);
        this.p = p3;
        final cjs q = new cjs(cjq);
        this.q = q;
        final cbp r = new cbp(g2, p3, q, 3, (char[])null);
        this.r = r;
        final pii b8 = oum.b(dnf.i(b7, r));
        this.s = b8;
        final dmr d = dmr.d(b8);
        this.t = d;
        final List k = pjv.j(1);
        final List l = pjv.j(2);
        pqf.h(a3, l);
        pqf.i(n, k);
        pqf.h(d, l);
        final ous g3 = pqf.g(k, l);
        this.u = g3;
        final pii b9 = oum.b(fyj.e(g3, b.aM));
        this.v = b9;
        final pii b10 = oum.b(div.a(b9));
        this.w = b10;
        final pii b11 = oum.b(dbt.c(g2, b5));
        this.x = b11;
        final pii b12 = oum.b(cbp.i(g2, b11, b9));
        this.y = b12;
        final List m = pjv.j(11);
        final List j2 = pjv.j(0);
        pqf.i(b.aN, m);
        pqf.i(b.aO, m);
        pqf.i(b.aP, m);
        pqf.i(b.aQ, m);
        pqf.i(b.aR, m);
        pqf.i(b.aS, m);
        pqf.i(b.aT, m);
        pqf.i(b.aW, m);
        pqf.i(b.ba, m);
        pqf.i(b.bd, m);
        pqf.i(b.bg, m);
        final ous g4 = pqf.g(m, j2);
        this.z = g4;
        final pii b13 = oum.b(diw.b(b10, b12, b5, g4));
        this.A = b13;
        final bob b14 = bob.b(b.bb, n2);
        this.B = b14;
        final bxh b15 = bxh.b(b.j, b5, b13, n2, b14, b6, b.o);
        this.C = b15;
        final pii b16 = oum.b(gdq.a);
        this.D = b16;
        final pii b17 = oum.b(fyj.c(b.I, b16));
        this.E = b17;
        final pii b18 = oum.b(new bnj(b.h, n2, b.j, b17, b.o, b.bh, 7, (float[])null));
        this.F = b18;
        this.G = oum.b(dnf.f(b.aV, b9));
        final pii b19 = oum.b(dnf.h(b.aV, b.j));
        this.H = b19;
        final pii b20 = oum.b(dmj.c(b.bi, p3, n2));
        this.I = b20;
        final pii b21 = oum.b(ied.c(b.Y, n2, b.j));
        this.J = b21;
        final pii b22 = oum.b(bnj.g(b.j, n2, b21, b.bi, b8, r));
        this.K = b22;
        final pii b23 = oum.b(new cbp(b19, b20, b22, 2, (byte[])null));
        this.L = b23;
        final fjp b24 = fjp.b(b23);
        this.M = b24;
        final pii b25 = oum.b(grt.i(b24));
        this.N = b25;
        final pii b26 = oum.b(hay.a);
        this.O = b26;
        final pii b27 = oum.b(gzy.a);
        this.P = b27;
        final gzt b28 = gzt.b(b.bj, b.bk, b.bl, b.bm);
        this.Q = b28;
        final pii c = emd.c(b.bc);
        this.R = c;
        final pii b29 = oum.b(ejv.a(b18, b25, b26, b27, b28, b.aZ, c, cno.a, b.bj, b.bn, b9));
        this.S = b29;
        final cnt t = new cnt(g2, b14, h, b29, b.bo, b21, b9);
        this.T = t;
        final cbk u = new cbk(q, t, 13, (boolean[])null);
        this.U = u;
        final cbl v = new cbl(q, 7);
        this.V = v;
        final pii b30 = oum.b(ezm.e(b23, v));
        this.W = b30;
        final cbk x = new cbk(b9, b30, 12, (int[])null);
        this.X = x;
        final List j3 = pjv.j(2);
        final List j4 = pjv.j(1);
        pqf.h(b15, j4);
        pqf.i(u, j3);
        pqf.i(x, j3);
        this.Y = pqf.g(j3, j4);
        final dmr c2 = dmr.c(b8);
        this.Z = c2;
        final List j5 = pjv.j(1);
        final List j6 = pjv.j(0);
        pqf.i(c2, j5);
        final ous g5 = pqf.g(j5, j6);
        this.aa = g5;
        final pii b31 = oum.b(diw.g(b7, b.bp, g5, ous.a));
        this.ab = b31;
        final dnf g6 = dnf.g(b7, b31);
        this.ac = g6;
        final List j7 = pjv.j(0);
        final List j8 = pjv.j(1);
        pqf.h(g6, j8);
        final ous g7 = pqf.g(j7, j8);
        this.ad = g7;
        final cju ae = new cju(cjq);
        this.ae = ae;
        this.af = oum.b(gsl.d(g7, ae));
    }
    
    @Override
    public final cjw a() {
        final cid a = this.a.a;
        pqf.k(a);
        nqb.C(3, "expectedSize");
        final nog nog = new nog(null);
        nog.i(dnf.b((cxl)this.b.j.get(), this.d));
        nog.g(fel.a((Executor)this.b.I.get(), (Executor)this.f.get(), this.Y, ous.a));
        nog.g(this.af.get());
        return new cjw(a, new gdi(nog.f(), (ofn)this.e.get(), (Executor)this.E.get(), (kse)this.b.o.get()), (kjk)this.v.get(), (ofn)this.D.get(), (kkp)this.b.aM.get());
    }
}
