// 
// Decompiled by Procyon v0.6.0
// 

public enum gjp
{
    A("FPS_60", 26), 
    B("RES_1080P", 27), 
    C("RES_2160P", 28), 
    D("BEAUTIFICATION_ON_LIGHT", 29), 
    E("BEAUTIFICATION_ON_STRONG", 30), 
    F("BEAUTIFICATION_OFF", 31), 
    G("MAKEUP_MAKEUP1", 32), 
    H("MAKEUP_MAKEUP2", 33), 
    I("MAKEUP_MAKEUP3", 34), 
    J("MAKEUP_OFF", 35), 
    K("ASTRO_AUTO", 36), 
    L("ASTRO_OFF", 37), 
    M("SWISS_ON", 38), 
    N("SWISS_OFF", 39), 
    O("AF_ON", 40), 
    P("AF_ON_LOCKED", 41), 
    Q("AF_OFF_NEAR", 42), 
    R("AF_OFF_FAR", 43), 
    S("AF_OFF_INFINITY", 44), 
    T("IMAX_AUDIO_ON", 45), 
    U("IMAX_AUDIO_OFF", 46), 
    V("SIXTEEN_BY_NINE", 47), 
    W("FOUR_BY_THREE", 48), 
    X("SELECTED", 49), 
    Y("UNSELECTED", 50), 
    Z("HORIZONTAL_PHOTO_SPHERE", 51), 
    a("UNKNOWN", 0), 
    aa("VERTICAL_PHOTO_SPHERE", 52), 
    ab("WIDE_ANGLE_PHOTO_SPHERE", 53), 
    ac("FISH_EYE_PHOTO_SPHERE", 54), 
    ad("PHOTO_SPHERE", 55), 
    b("TIMER_ZERO_SECONDS", 1), 
    c("TIMER_THREE_SECONDS", 2), 
    d("TIMER_TEN_SECONDS", 3), 
    e("TIMER_AUTO", 4), 
    f("HDR_AUTO", 5), 
    g("HDR_ON", 6), 
    h("HDR_OFF", 7), 
    i("HDR_READY", 8), 
    j("PHOTO_FLASH_ON", 9), 
    k("PHOTO_FLASH_OFF", 10), 
    l("PHOTO_FLASH_AUTO", 11), 
    m("PHOTO_FLASH_NS", 12), 
    n("PHOTO_FLASH_GRAYED", 13), 
    o("PHOTO_FLASH_UNGRAYED", 14), 
    p("VIDEO_FLASH_ON", 15), 
    q("VIDEO_FLASH_OFF", 16), 
    r("MICROVIDEO_ON", 17), 
    s("MICROVIDEO_AUTO", 18), 
    t("MICROVIDEO_OFF", 19), 
    u("MIC_INPUT_PHONE", 20), 
    v("MIC_INPUT_EXT_WIRED", 21), 
    w("MIC_INPUT_EXT_BLUETOOTH", 22), 
    x("FPS_AUTO", 23), 
    y("FPS_24", 24), 
    z("FPS_30", 25);
    
    private gjp(final String s, final int n) {
    }
}
